// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web =  FirebaseOptions(
    apiKey: 'AIzaSyDoo59yQOI-tCUruQa_mc1Fb4KcYDp16ns',
    appId: '1:617861172627:web:912d0b668a9779c7c16c66',
    messagingSenderId: '617861172627',
    projectId: 'splitwise-cac10',
    authDomain: 'splitwise-cac10.firebaseapp.com',
    storageBucket: 'splitwise-cac10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSmvnBpe3lkrLg3F7wmu1i9VQDWwy9dw',
    appId: '1:617861172627:android:b3b3ad995d3e5393c16c66',
    messagingSenderId: '617861172627',
    projectId: 'splitwise-cac10',
    storageBucket: 'splitwise-cac10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAawQl5BKBglp2RNtba0cNXqxm78kJyVfY',
    appId: '1:617861172627:ios:425935605453a822c16c66',
    messagingSenderId: '617861172627',
    projectId: 'splitwise-cac10',
    storageBucket: 'splitwise-cac10.appspot.com',
    iosBundleId: 'com.example.splitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAawQl5BKBglp2RNtba0cNXqxm78kJyVfY',
    appId: '1:617861172627:ios:a388e6f09d223f58c16c66',
    messagingSenderId: '617861172627',
    projectId: 'splitwise-cac10',
    storageBucket: 'splitwise-cac10.appspot.com',
    iosBundleId: 'com.example.splitwise.RunnerTests',
  );
}
